name: Generate gallery.json

on:
  push:
    paths:
      - 'images/**'    # images folder repo root ma che

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate gallery.json
      run: |
        FILES=$(ls images)
        echo "[" > gallery/gallery.json
        COUNT=0
        for FILE in $FILES
        do
          if [ $COUNT -gt 0 ]; then echo "," >> gallery/gallery.json; fi
          echo "  {" >> gallery/gallery.json
          echo "    \"src\": \"../images/$FILE\"," >> gallery/gallery.json
          echo "    \"title\": \"Photo $((COUNT+1))\"," >> gallery/gallery.json
          echo "    \"year\": \"2025\"," >> gallery/gallery.json
          echo "    \"alt\": \"Photo number $((COUNT+1)) by Keval Kotadia\"" >> gallery/gallery.json
          echo "  }" >> gallery/gallery.json
          COUNT=$((COUNT+1))
        done
        echo "]" >> gallery/gallery.json
    - name: Commit changes
 run: |
    git config --local user.email "action@github.com"
    git config --local user.name "GitHub Action"
    git add gallery/gallery.json
    git commit -m "Auto-update gallery.json"
    git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/india8155/keval-photography.git HEAD:main
 continue-on-error: true

